FROM node:20-alpine

ARG ZENDESK_URL
ARG ZENDESK_TOKEN
ARG NEXT_PUBLIC_API_DOMAIN
ARG NEXT_SHARP_PATH

RUN apk add --no-cache git

WORKDIR /app

COPY . ./

ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV production

ENV ZENDESK_URL=$ZENDESK_URL
ENV ZENDESK_TOKEN=$ZENDESK_TOKEN
ENV NEXT_PUBLIC_API_DOMAIN=$NEXT_PUBLIC_API_DOMAIN
ENV NEXT_SHARP_PATH=$NEXT_SHARP_PATH

RUN yarn install --frozen-lockfile

RUN yarn build

CMD [ "yarn", "start" ]
