FROM node:20-alpine AS base

ARG ZENDESK_URL
ARG ZENDESK_TOKEN
ARG NEXT_PUBLIC_API_DOMAIN
ARG NEXT_SHARP_PATH

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY yarn.lock* ./
RUN yarn install --frozen-lockfile

WORKDIR /app
COPY . ./

ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV production
ENV NEXT_SHARP_PATH $NEXT_SHARP_PATH

ENV ZENDESK_URL=$ZENDESK_URL
ENV ZENDESK_TOKEN=$ZENDESK_TOKEN
ENV NEXT_PUBLIC_API_DOMAIN=$NEXT_PUBLIC_API_DOMAIN

RUN yarn build

CMD [ "yarn", "start" ]
