import { Country } from '@/types/country';

export const COUNTRIES_LIST: Country[] = [
    {
        codeIso: 'AF',
        title: 'افغانستان',
        titleEn: 'Afghanistan',
        phoneCode: '+93',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/af.svg',
    },
    {
        codeIso: 'AX',
        title: 'Åland',
        titleEn: 'Aland Islands',
        phoneCode: '+358',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ax.svg',
    },
    {
        codeIso: 'AL',
        title: 'Shqipëri',
        titleEn: 'Albania',
        phoneCode: '+355',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/al.svg',
    },
    {
        codeIso: 'DZ',
        title: 'الجزائر',
        titleEn: 'Algeria',
        phoneCode: '+213',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/dz.svg',
    },
    {
        codeIso: 'AS',
        title: 'American Samoa',
        titleEn: 'AmericanSamoa',
        phoneCode: '+1 684',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/as.svg',
    },
    {
        codeIso: 'AD',
        title: 'Andorra',
        titleEn: 'Andorra',
        phoneCode: '+376',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ad.svg',
    },
    {
        codeIso: 'AO',
        title: 'Angola',
        titleEn: 'Angola',
        phoneCode: '+244',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ao.svg',
    },
    {
        codeIso: 'AI',
        title: 'Anguilla',
        titleEn: 'Anguilla',
        phoneCode: '+1 264',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ai.svg',
    },
    {
        codeIso: 'AQ',
        title: 'Antarctica',
        titleEn: 'Antarctica',
        phoneCode: '+672',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/aq.svg',
    },
    {
        codeIso: 'AG',
        title: 'Antigua and Barbuda',
        titleEn: 'Antigua and Barbuda',
        phoneCode: '+1268',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ag.svg',
    },
    {
        codeIso: 'AR',
        title: 'Argentina',
        titleEn: 'Argentina',
        phoneCode: '+54',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ar.svg',
    },
    {
        codeIso: 'AM',
        title: 'Հայաստան',
        titleEn: 'Armenia',
        phoneCode: '+374',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/am.svg',
    },
    {
        codeIso: 'AW',
        title: 'Aruba',
        titleEn: 'Aruba',
        phoneCode: '+297',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/aw.svg',
    },
    {
        codeIso: 'AU',
        title: 'Australia',
        titleEn: 'Australia',
        phoneCode: '+61',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/au.svg',
    },
    {
        codeIso: 'AT',
        title: 'Österreich',
        titleEn: 'Austria',
        phoneCode: '+43',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/at.svg',
    },
    {
        codeIso: 'AZ',
        title: 'Azərbaycan',
        titleEn: 'Azerbaijan',
        phoneCode: '+994',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/az.svg',
    },
    {
        codeIso: 'BS',
        title: 'Bahamas',
        titleEn: 'Bahamas',
        phoneCode: '+1 242',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/bs.svg',
    },
    {
        codeIso: 'BH',
        title: 'البحرين',
        titleEn: 'Bahrain',
        phoneCode: '+973',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/bh.svg',
    },
    {
        codeIso: 'BD',
        title: 'বাংলাদেশ',
        titleEn: 'Bangladesh',
        phoneCode: '+880',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/bd.svg',
    },
    {
        codeIso: 'BB',
        title: 'Barbados',
        titleEn: 'Barbados',
        phoneCode: '+1 246',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/bb.svg',
    },
    {
        codeIso: 'BY',
        title: 'Беларусь',
        titleEn: 'Belarus',
        phoneCode: '+375',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/by.svg',
    },
    {
        codeIso: 'BE',
        title: 'België',
        titleEn: 'Belgium',
        phoneCode: '+32',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/be.svg',
    },
    {
        codeIso: 'BZ',
        title: 'Belize',
        titleEn: 'Belize',
        phoneCode: '+501',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/bz.svg',
    },
    {
        codeIso: 'BJ',
        title: 'Bénin',
        titleEn: 'Benin',
        phoneCode: '+229',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/bj.svg',
    },
    {
        codeIso: 'BM',
        title: 'Bermuda',
        titleEn: 'Bermuda',
        phoneCode: '+1 441',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/bm.svg',
    },
    {
        codeIso: 'BT',
        title: 'འབྲུག་ཡུལ།',
        titleEn: 'Bhutan',
        phoneCode: '+975',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/bt.svg',
    },
    {
        codeIso: 'BO',
        title: 'Estado Plurinacional de Bolivia',
        titleEn: 'Bolivia, Plurinational State of',
        phoneCode: '+591',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/bo.svg',
    },
    {
        codeIso: 'BA',
        title: 'Bosna i Hercegovina',
        titleEn: 'Bosnia and Herzegovina',
        phoneCode: '+387',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ba.svg',
    },
    {
        codeIso: 'BW',
        title: 'Botswana',
        titleEn: 'Botswana',
        phoneCode: '+267',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/bw.svg',
    },
    {
        codeIso: 'BR',
        title: 'Brasil',
        titleEn: 'Brazil',
        phoneCode: '+55',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/br.svg',
    },
    {
        codeIso: 'IO',
        title: 'British Indian Ocean Territory',
        titleEn: 'British Indian Ocean Territory',
        phoneCode: '+246',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/io.svg',
    },
    {
        codeIso: 'BN',
        title: 'Brunei Darussalam',
        titleEn: 'Brunei Darussalam',
        phoneCode: '+673',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/bn.svg',
    },
    {
        codeIso: 'BG',
        title: 'България',
        titleEn: 'Bulgaria',
        phoneCode: '+359',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/bg.svg',
    },
    {
        codeIso: 'BF',
        title: 'Burkina Fasо',
        titleEn: 'Burkina Faso',
        phoneCode: '+226',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/bf.svg',
    },
    {
        codeIso: 'BI',
        title: 'Burundi',
        titleEn: 'Burundi',
        phoneCode: '+257',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/bi.svg',
    },
    {
        codeIso: 'KH',
        title: 'កម្ពុជា',
        titleEn: 'Cambodia',
        phoneCode: '+855',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/kh.svg',
    },
    {
        codeIso: 'CM',
        title: 'Cameroon',
        titleEn: 'Cameroon',
        phoneCode: '+237',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/cm.svg',
    },
    {
        codeIso: 'CA',
        title: 'Canada',
        titleEn: 'Canada',
        phoneCode: '+1',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ca.svg',
    },
    {
        codeIso: 'CV',
        title: 'Cabo Verde',
        titleEn: 'Cape Verde',
        phoneCode: '+238',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/cv.svg',
    },
    {
        codeIso: 'KY',
        title: 'Cayman Islands',
        titleEn: 'Cayman Islands',
        phoneCode: '+ 345',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ky.svg',
    },
    {
        codeIso: 'CF',
        title: 'République centrafricaine',
        titleEn: 'Central African Republic',
        phoneCode: '+236',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/cf.svg',
    },
    {
        codeIso: 'TD',
        title: 'Tchad',
        titleEn: 'Chad',
        phoneCode: '+235',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/td.svg',
    },
    {
        codeIso: 'CL',
        title: 'Chile',
        titleEn: 'Chile',
        phoneCode: '+56',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/cl.svg',
    },
    {
        codeIso: 'CN',
        title: '中国',
        titleEn: 'China',
        phoneCode: '+86',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/cn.svg',
    },
    {
        codeIso: 'CX',
        title: 'Christmas Island',
        titleEn: 'Christmas Island',
        phoneCode: '+61',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/cx.svg',
    },
    {
        codeIso: 'CC',
        title: 'Cocos (Keeling) Islands',
        titleEn: 'Cocos (Keeling) Islands',
        phoneCode: '+61',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/cc.svg',
    },
    {
        codeIso: 'CO',
        title: 'Colombia',
        titleEn: 'Colombia',
        phoneCode: '+57',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/co.svg',
    },
    {
        codeIso: 'KM',
        title: 'جزر القمر',
        titleEn: 'Comoros',
        phoneCode: '+269',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/km.svg',
    },
    {
        codeIso: 'CG',
        title: 'Congo',
        titleEn: 'Congo',
        phoneCode: '+242',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/cg.svg',
    },
    {
        codeIso: 'CD',
        title: 'Congo, République démocratique du Congo',
        titleEn: 'Congo, The Democratic Republic of the Congo',
        phoneCode: '+243',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/cd.svg',
    },
    {
        codeIso: 'CK',
        title: 'Cook Islands',
        titleEn: 'Cook Islands',
        phoneCode: '+682',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ck.svg',
    },
    {
        codeIso: 'CR',
        title: 'Costa Rica',
        titleEn: 'Costa Rica',
        phoneCode: '+506',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/cr.svg',
    },
    {
        codeIso: 'CI',
        title: "Côte d'Ivoire",
        titleEn: "Cote d'Ivoire",
        phoneCode: '+225',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ci.svg',
    },
    {
        codeIso: 'HR',
        title: 'Hrvatska',
        titleEn: 'Croatia',
        phoneCode: '+385',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/hr.svg',
    },
    {
        codeIso: 'CU',
        title: 'Cuba',
        titleEn: 'Cuba',
        phoneCode: '+53',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/cu.svg',
    },
    {
        codeIso: 'CY',
        title: 'Κύπρος',
        titleEn: 'Cyprus',
        phoneCode: '+357',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/cy.svg',
    },
    {
        codeIso: 'CZ',
        title: 'Česká republika',
        titleEn: 'Czech Republic',
        phoneCode: '+420',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/cz.svg',
    },
    {
        codeIso: 'DK',
        title: 'Danmark',
        titleEn: 'Denmark',
        phoneCode: '+45',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/dk.svg',
    },
    {
        codeIso: 'DJ',
        title: 'جيبوتي',
        titleEn: 'Djibouti',
        phoneCode: '+253',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/dj.svg',
    },
    {
        codeIso: 'DM',
        title: 'Dominica',
        titleEn: 'Dominica',
        phoneCode: '+1 767',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/dm.svg',
    },
    {
        codeIso: 'DO',
        title: 'República Dominicana',
        titleEn: 'Dominican Republic',
        phoneCode: '+1 849',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/do.svg',
    },
    {
        codeIso: 'EC',
        title: 'Ecuador',
        titleEn: 'Ecuador',
        phoneCode: '+593',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ec.svg',
    },
    {
        codeIso: 'EG',
        title: 'مصر',
        titleEn: 'Egypt',
        phoneCode: '+20',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/eg.svg',
    },
    {
        codeIso: 'SV',
        title: 'El Salvador',
        titleEn: 'El Salvador',
        phoneCode: '+503',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/sv.svg',
    },
    {
        codeIso: 'GQ',
        title: 'Guinea Ecuatorial',
        titleEn: 'Equatorial Guinea',
        phoneCode: '+240',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/gq.svg',
    },
    {
        codeIso: 'ER',
        title: 'ኤርትራ',
        titleEn: 'Eritrea',
        phoneCode: '+291',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/er.svg',
    },
    {
        codeIso: 'EE',
        title: 'Eesti',
        titleEn: 'Estonia',
        phoneCode: '+372',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ee.svg',
    },
    {
        codeIso: 'ET',
        title: 'ኢትዮጵያ',
        titleEn: 'Ethiopia',
        phoneCode: '+251',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/et.svg',
    },
    {
        codeIso: 'FK',
        title: 'Falkland Islands',
        titleEn: 'Falkland Islands (Malvinas)',
        phoneCode: '+500',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/fk.svg',
    },
    {
        codeIso: 'FO',
        title: 'Føroyar',
        titleEn: 'Faroe Islands',
        phoneCode: '+298',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/fo.svg',
    },
    {
        codeIso: 'FJ',
        title: 'Viti',
        titleEn: 'Fiji',
        phoneCode: '+679',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/fj.svg',
    },
    {
        codeIso: 'FI',
        title: 'Suomi',
        titleEn: 'Finland',
        phoneCode: '+358',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/fi.svg',
    },
    {
        codeIso: 'FR',
        title: 'France',
        titleEn: 'France',
        phoneCode: '+33',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/fr.svg',
    },
    {
        codeIso: 'GF',
        title: 'Guyane français',
        titleEn: 'French Guiana',
        phoneCode: '+594',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/gf.svg',
    },
    {
        codeIso: 'PF',
        title: 'Polynésie française',
        titleEn: 'French Polynesia',
        phoneCode: '+689',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/pf.svg',
    },
    {
        codeIso: 'GA',
        title: 'Gabon',
        titleEn: 'Gabon',
        phoneCode: '+241',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ga.svg',
    },
    {
        codeIso: 'GM',
        title: 'Gambia',
        titleEn: 'Gambia',
        phoneCode: '+220',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/gm.svg',
    },
    {
        codeIso: 'GE',
        title: 'საქართველო',
        titleEn: 'Georgia',
        phoneCode: '+995',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ge.svg',
    },
    {
        codeIso: 'DE',
        title: 'Deutschland',
        titleEn: 'Germany',
        phoneCode: '+49',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/de.svg',
    },
    {
        codeIso: 'GH',
        title: 'Ghana',
        titleEn: 'Ghana',
        phoneCode: '+233',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/gh.svg',
    },
    {
        codeIso: 'GI',
        title: 'Gibraltar',
        titleEn: 'Gibraltar',
        phoneCode: '+350',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/gi.svg',
    },
    {
        codeIso: 'GR',
        title: 'Ελλάδα',
        titleEn: 'Greece',
        phoneCode: '+30',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/gr.svg',
    },
    {
        codeIso: 'GL',
        title: 'Kalaallit Nunaat',
        titleEn: 'Greenland',
        phoneCode: '+299',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/gl.svg',
    },
    {
        codeIso: 'GD',
        title: 'Grenada',
        titleEn: 'Grenada',
        phoneCode: '+1 473',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/gd.svg',
    },
    {
        codeIso: 'GP',
        title: 'Guadeloupe',
        titleEn: 'Guadeloupe',
        phoneCode: '+590',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/gp.svg',
    },
    {
        codeIso: 'GU',
        title: 'Guam',
        titleEn: 'Guam',
        phoneCode: '+1 671',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/gu.svg',
    },
    {
        codeIso: 'GT',
        title: 'Guatemala',
        titleEn: 'Guatemala',
        phoneCode: '+502',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/gt.svg',
    },
    {
        codeIso: 'GG',
        title: 'Guernsey',
        titleEn: 'Guernsey',
        phoneCode: '+44',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/gg.svg',
    },
    {
        codeIso: 'GN',
        title: 'Guinée',
        titleEn: 'Guinea',
        phoneCode: '+224',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/gn.svg',
    },
    {
        codeIso: 'GW',
        title: 'Guiné-Bissau',
        titleEn: 'Guinea-Bissau',
        phoneCode: '+245',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/gw.svg',
    },
    {
        codeIso: 'GY',
        title: 'Guyana',
        titleEn: 'Guyana',
        phoneCode: '+595',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/gy.svg',
    },
    {
        codeIso: 'HT',
        title: 'Haïti',
        titleEn: 'Haiti',
        phoneCode: '+509',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ht.svg',
    },
    {
        codeIso: 'VA',
        title: 'Città del Vaticano',
        titleEn: 'Holy See (Vatican City State)',
        phoneCode: '+379',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/va.svg',
    },
    {
        codeIso: 'HN',
        title: 'Honduras',
        titleEn: 'Honduras',
        phoneCode: '+504',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/hn.svg',
    },
    {
        codeIso: 'HK',
        title: '香港',
        titleEn: 'Hong Kong',
        phoneCode: '+852',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/hk.svg',
    },
    {
        codeIso: 'HU',
        title: 'Magyarország',
        titleEn: 'Hungary',
        phoneCode: '+36',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/hu.svg',
    },
    {
        codeIso: 'IS',
        title: 'Ísland',
        titleEn: 'Iceland',
        phoneCode: '+354',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/is.svg',
    },
    {
        codeIso: 'IN',
        title: 'भारत',
        titleEn: 'India',
        phoneCode: '+91',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/in.svg',
    },
    {
        codeIso: 'ID',
        title: 'Indonesia',
        titleEn: 'Indonesia',
        phoneCode: '+62',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/id.svg',
    },
    {
        codeIso: 'IR',
        title: 'ایران',
        titleEn: 'Iran, Islamic Republic of Persian Gulf',
        phoneCode: '+98',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ir.svg',
    },
    {
        codeIso: 'IQ',
        title: 'العراق',
        titleEn: 'Iraq',
        phoneCode: '+964',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/iq.svg',
    },
    {
        codeIso: 'IE',
        title: 'Ireland',
        titleEn: 'Ireland',
        phoneCode: '+353',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ie.svg',
    },
    {
        codeIso: 'IM',
        title: 'Isle of Man',
        titleEn: 'Isle of Man',
        phoneCode: '+44',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/im.svg',
    },
    {
        codeIso: 'IL',
        title: 'ישראל',
        titleEn: 'Israel',
        phoneCode: '+972',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/il.svg',
    },
    {
        codeIso: 'IT',
        title: 'Italia',
        titleEn: 'Italy',
        phoneCode: '+39',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/it.svg',
    },
    {
        codeIso: 'JM',
        title: 'Jamaica',
        titleEn: 'Jamaica',
        phoneCode: '+1 876',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/jm.svg',
    },
    {
        codeIso: 'JP',
        title: '日本',
        titleEn: 'Japan',
        phoneCode: '+81',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/jp.svg',
    },
    {
        codeIso: 'JE',
        title: 'Jersey',
        titleEn: 'Jersey',
        phoneCode: '+44',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/je.svg',
    },
    {
        codeIso: 'JO',
        title: 'الأردن',
        titleEn: 'Jordan',
        phoneCode: '+962',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/jo.svg',
    },
    {
        codeIso: 'KZ',
        title: 'Қазақстан',
        titleEn: 'Kazakhstan',
        phoneCode: '+7 7',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/kz.svg',
    },
    {
        codeIso: 'KE',
        title: 'Kenya',
        titleEn: 'Kenya',
        phoneCode: '+254',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ke.svg',
    },
    {
        codeIso: 'KI',
        title: 'Kiribati',
        titleEn: 'Kiribati',
        phoneCode: '+686',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ki.svg',
    },
    {
        codeIso: 'KP',
        title: '조선민주주의인민공화국',
        titleEn: "Korea, Democratic People's Republic of Korea",
        phoneCode: '+850',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/kp.svg',
    },
    {
        codeIso: 'KR',
        title: '대한민국',
        titleEn: 'Korea, Republic of South Korea',
        phoneCode: '+82',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/kr.svg',
    },
    {
        codeIso: 'XK',
        title: 'Kosova',
        titleEn: 'Kosovo',
        phoneCode: '+383',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/xk.svg',
    },
    {
        codeIso: 'KW',
        title: 'الكويت',
        titleEn: 'Kuwait',
        phoneCode: '+965',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/kw.svg',
    },
    {
        codeIso: 'KG',
        title: 'Кыргызстан',
        titleEn: 'Kyrgyzstan',
        phoneCode: '+996',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/kg.svg',
    },
    {
        codeIso: 'LA',
        title: 'ລາວ',
        titleEn: 'Laos',
        phoneCode: '+856',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/la.svg',
    },
    {
        codeIso: 'LV',
        title: 'Latvija',
        titleEn: 'Latvia',
        phoneCode: '+371',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/lv.svg',
    },
    {
        codeIso: 'LB',
        title: 'لبنان',
        titleEn: 'Lebanon',
        phoneCode: '+961',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/lb.svg',
    },
    {
        codeIso: 'LS',
        title: 'Lesotho',
        titleEn: 'Lesotho',
        phoneCode: '+266',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ls.svg',
    },
    {
        codeIso: 'LR',
        title: 'Liberia',
        titleEn: 'Liberia',
        phoneCode: '+231',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/lr.svg',
    },
    {
        codeIso: 'LY',
        title: 'ليبيا',
        titleEn: 'Libyan Arab Jamahiriya',
        phoneCode: '+218',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ly.svg',
    },
    {
        codeIso: 'LI',
        title: 'Liechtenstein',
        titleEn: 'Liechtenstein',
        phoneCode: '+423',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/li.svg',
    },
    {
        codeIso: 'LT',
        title: 'Lietuva',
        titleEn: 'Lithuania',
        phoneCode: '+370',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/lt.svg',
    },
    {
        codeIso: 'LU',
        title: 'Luxembourg',
        titleEn: 'Luxembourg',
        phoneCode: '+352',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/lu.svg',
    },
    {
        codeIso: 'MO',
        title: '澳門',
        titleEn: 'Macao',
        phoneCode: '+853',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/mo.svg',
    },
    {
        codeIso: 'MK',
        title: 'Македонија',
        titleEn: 'Macedonia',
        phoneCode: '+389',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/mk.svg',
    },
    {
        codeIso: 'MG',
        title: 'Madagasikara',
        titleEn: 'Madagascar',
        phoneCode: '+261',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/mg.svg',
    },
    {
        codeIso: 'MW',
        title: 'Malawi',
        titleEn: 'Malawi',
        phoneCode: '+265',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/mw.svg',
    },
    {
        codeIso: 'MY',
        title: 'Malaysia',
        titleEn: 'Malaysia',
        phoneCode: '+60',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/my.svg',
    },
    {
        codeIso: 'MV',
        title: 'ދިވެހިރާއްޖެ',
        titleEn: 'Maldives',
        phoneCode: '+960',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/mv.svg',
    },
    {
        codeIso: 'ML',
        title: 'Mali',
        titleEn: 'Mali',
        phoneCode: '+223',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ml.svg',
    },
    {
        codeIso: 'MT',
        title: 'Malta',
        titleEn: 'Malta',
        phoneCode: '+356',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/mt.svg',
    },
    {
        codeIso: 'MH',
        title: 'Aelōn̄ in M̧ajeļ',
        titleEn: 'Marshall Islands',
        phoneCode: '+692',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/mh.svg',
    },
    {
        codeIso: 'MQ',
        title: 'Martinique',
        titleEn: 'Martinique',
        phoneCode: '+596',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/mq.svg',
    },
    {
        codeIso: 'MR',
        title: 'موريتانيا',
        titleEn: 'Mauritania',
        phoneCode: '+222',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/mr.svg',
    },
    {
        codeIso: 'MU',
        title: 'Moris',
        titleEn: 'Mauritius',
        phoneCode: '+230',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/mu.svg',
    },
    {
        codeIso: 'YT',
        title: 'Mayotte',
        titleEn: 'Mayotte',
        phoneCode: '+262',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/yt.svg',
    },
    {
        codeIso: 'MX',
        title: 'México',
        titleEn: 'Mexico',
        phoneCode: '+52',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/mx.svg',
    },
    {
        codeIso: 'FM',
        title: 'Micronesia',
        titleEn: 'Micronesia, Federated States of Micronesia',
        phoneCode: '+691',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/fm.svg',
    },
    {
        codeIso: 'MD',
        title: 'Moldova',
        titleEn: 'Moldova',
        phoneCode: '+373',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/md.svg',
    },
    {
        codeIso: 'MC',
        title: 'Monaco',
        titleEn: 'Monaco',
        phoneCode: '+377',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/mc.svg',
    },
    {
        codeIso: 'MN',
        title: 'Монгол улс',
        titleEn: 'Mongolia',
        phoneCode: '+976',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/mn.svg',
    },
    {
        codeIso: 'ME',
        title: 'Црна Гора',
        titleEn: 'Montenegro',
        phoneCode: '+382',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/me.svg',
    },
    {
        codeIso: 'MS',
        title: 'Montserrat',
        titleEn: 'Montserrat',
        phoneCode: '+1664',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ms.svg',
    },
    {
        codeIso: 'MA',
        title: 'المغرب',
        titleEn: 'Morocco',
        phoneCode: '+212',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ma.svg',
    },
    {
        codeIso: 'MZ',
        title: 'Moçambique',
        titleEn: 'Mozambique',
        phoneCode: '+258',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/mz.svg',
    },
    {
        codeIso: 'MM',
        title: 'မြန်မာ',
        titleEn: 'Myanmar',
        phoneCode: '+95',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/mm.svg',
    },
    {
        codeIso: 'NA',
        title: 'Namibia',
        titleEn: 'Namibia',
        phoneCode: '+264',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/na.svg',
    },
    {
        codeIso: 'NR',
        title: 'Naoero',
        titleEn: 'Nauru',
        phoneCode: '+674',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/nr.svg',
    },
    {
        codeIso: 'NP',
        title: 'नेपाल',
        titleEn: 'Nepal',
        phoneCode: '+977',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/np.svg',
    },
    {
        codeIso: 'NL',
        title: 'Nederland',
        titleEn: 'Netherlands',
        phoneCode: '+31',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/nl.svg',
    },
    {
        codeIso: 'AN',
        title: 'Netherlands Antilles',
        titleEn: 'Netherlands Antilles',
        phoneCode: '+599',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/an.svg',
    },
    {
        codeIso: 'NC',
        title: 'Nouvelle-Calédonie',
        titleEn: 'New Caledonia',
        phoneCode: '+687',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/nc.svg',
    },
    {
        codeIso: 'NZ',
        title: 'New Zealand',
        titleEn: 'New Zealand',
        phoneCode: '+64',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/nz.svg',
    },
    {
        codeIso: 'NI',
        title: 'Nicaragua',
        titleEn: 'Nicaragua',
        phoneCode: '+505',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ni.svg',
    },
    {
        codeIso: 'NE',
        title: 'Niger',
        titleEn: 'Niger',
        phoneCode: '+227',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ne.svg',
    },
    {
        codeIso: 'NG',
        title: 'Nigeria',
        titleEn: 'Nigeria',
        phoneCode: '+234',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ng.svg',
    },
    {
        codeIso: 'NU',
        title: 'Niue',
        titleEn: 'Niue',
        phoneCode: '+683',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/nu.svg',
    },
    {
        codeIso: 'NF',
        title: 'Norfolk Island',
        titleEn: 'Norfolk Island',
        phoneCode: '+672',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/nf.svg',
    },
    {
        codeIso: 'MP',
        title: 'Northern Mariana Islands',
        titleEn: 'Northern Mariana Islands',
        phoneCode: '+1 670',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/mp.svg',
    },
    {
        codeIso: 'NO',
        title: 'Norge',
        titleEn: 'Norway',
        phoneCode: '+47',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/no.svg',
    },
    {
        codeIso: 'OM',
        title: 'عمان',
        titleEn: 'Oman',
        phoneCode: '+968',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/om.svg',
    },
    {
        codeIso: 'PK',
        title: 'پاکستان',
        titleEn: 'Pakistan',
        phoneCode: '+92',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/pk.svg',
    },
    {
        codeIso: 'PW',
        title: 'Belau',
        titleEn: 'Palau',
        phoneCode: '+680',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/pw.svg',
    },
    {
        codeIso: 'PS',
        title: 'فلسطين',
        titleEn: 'Palestinian Territory, Occupied',
        phoneCode: '+970',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ps.svg',
    },
    {
        codeIso: 'PA',
        title: 'Panamá',
        titleEn: 'Panama',
        phoneCode: '+507',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/pa.svg',
    },
    {
        codeIso: 'PG',
        title: 'Papua Niugini',
        titleEn: 'Papua New Guinea',
        phoneCode: '+675',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/pg.svg',
    },
    {
        codeIso: 'PY',
        title: 'Paraguay',
        titleEn: 'Paraguay',
        phoneCode: '+595',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/py.svg',
    },
    {
        codeIso: 'PE',
        title: 'Perú',
        titleEn: 'Peru',
        phoneCode: '+51',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/pe.svg',
    },
    {
        codeIso: 'PH',
        title: 'Pilipinas',
        titleEn: 'Philippines',
        phoneCode: '+63',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ph.svg',
    },
    {
        codeIso: 'PN',
        title: 'Pitcairn Islands',
        titleEn: 'Pitcairn',
        phoneCode: '+872',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/pn.svg',
    },
    {
        codeIso: 'PL',
        title: 'Polska',
        titleEn: 'Poland',
        phoneCode: '+48',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/pl.svg',
    },
    {
        codeIso: 'PT',
        title: 'Portugal',
        titleEn: 'Portugal',
        phoneCode: '+351',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/pt.svg',
    },
    {
        codeIso: 'PR',
        title: 'Puerto Rico',
        titleEn: 'Puerto Rico',
        phoneCode: '+1 939',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/pr.svg',
    },
    {
        codeIso: 'QA',
        title: 'قطر',
        titleEn: 'Qatar',
        phoneCode: '+974',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/qa.svg',
    },
    {
        codeIso: 'RO',
        title: 'România',
        titleEn: 'Romania',
        phoneCode: '+40',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ro.svg',
    },
    {
        codeIso: 'RU',
        title: 'Российская Федерация',
        titleEn: 'Russia',
        phoneCode: '+7',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ru.svg',
    },
    {
        codeIso: 'RW',
        title: 'Rwanda',
        titleEn: 'Rwanda',
        phoneCode: '+250',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/rw.svg',
    },
    {
        codeIso: 'RE',
        title: 'La Réunion',
        titleEn: 'Reunion',
        phoneCode: '+262',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/re.svg',
    },
    {
        codeIso: 'BL',
        title: 'Saint-Barthélemy',
        titleEn: 'Saint Barthelemy',
        phoneCode: '+590',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/bl.svg',
    },
    {
        codeIso: 'SH',
        title: 'Saint Helena, Ascension and Tristan da Cunha',
        titleEn: 'Saint Helena, Ascension and Tristan Da Cunha',
        phoneCode: '+290',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/sh.svg',
    },
    {
        codeIso: 'KN',
        title: 'Saint Kitts and Nevis',
        titleEn: 'Saint Kitts and Nevis',
        phoneCode: '+1 869',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/kn.svg',
    },
    {
        codeIso: 'LC',
        title: 'Saint Lucia',
        titleEn: 'Saint Lucia',
        phoneCode: '+1 758',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/lc.svg',
    },
    {
        codeIso: 'MF',
        title: 'Saint Martin',
        titleEn: 'Saint Martin',
        phoneCode: '+590',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/mf.svg',
    },
    {
        codeIso: 'PM',
        title: 'Saint Pierre and Miquelon',
        titleEn: 'Saint Pierre and Miquelon',
        phoneCode: '+508',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/pm.svg',
    },
    {
        codeIso: 'VC',
        title: 'Saint Vincent and the Grenadines',
        titleEn: 'Saint Vincent and the Grenadines',
        phoneCode: '+1 784',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/vc.svg',
    },
    {
        codeIso: 'WS',
        title: 'Samoa',
        titleEn: 'Samoa',
        phoneCode: '+685',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ws.svg',
    },
    {
        codeIso: 'SM',
        title: 'San Marino',
        titleEn: 'San Marino',
        phoneCode: '+378',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/sm.svg',
    },
    {
        codeIso: 'ST',
        title: 'São Tomé and Príncipe',
        titleEn: 'Sao Tome and Principe',
        phoneCode: '+239',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/st.svg',
    },
    {
        codeIso: 'SA',
        title: 'المملكة العربية السعودية',
        titleEn: 'Saudi Arabia',
        phoneCode: '+966',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/sa.svg',
    },
    {
        codeIso: 'SN',
        title: 'Sénégal',
        titleEn: 'Senegal',
        phoneCode: '+221',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/sn.svg',
    },
    {
        codeIso: 'RS',
        title: 'Србија',
        titleEn: 'Serbia',
        phoneCode: '+381',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/rs.svg',
    },
    {
        codeIso: 'SC',
        title: 'Seychelles',
        titleEn: 'Seychelles',
        phoneCode: '+248',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/sc.svg',
    },
    {
        codeIso: 'SL',
        title: 'Sierra Leone',
        titleEn: 'Sierra Leone',
        phoneCode: '+232',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/sl.svg',
    },
    {
        codeIso: 'SG',
        title: 'Singapore',
        titleEn: 'Singapore',
        phoneCode: '+65',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/sg.svg',
    },
    {
        codeIso: 'SK',
        title: 'Slovensko',
        titleEn: 'Slovakia',
        phoneCode: '+421',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/sk.svg',
    },
    {
        codeIso: 'SI',
        title: 'Slovenija',
        titleEn: 'Slovenia',
        phoneCode: '+386',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/si.svg',
    },
    {
        codeIso: 'SB',
        title: 'Solomon Islands',
        titleEn: 'Solomon Islands',
        phoneCode: '+677',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/sb.svg',
    },
    {
        codeIso: 'SO',
        title: 'Soomaaliya',
        titleEn: 'Somalia',
        phoneCode: '+252',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/so.svg',
    },
    {
        codeIso: 'ZA',
        title: 'South Africa',
        titleEn: 'South Africa',
        phoneCode: '+27',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/za.svg',
    },
    {
        codeIso: 'GS',
        title: 'South Georgia and the South Sandwich Islands',
        titleEn: 'South Georgia and the South Sandwich Islands',
        phoneCode: '+500',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/gs.svg',
    },
    {
        codeIso: 'ES',
        title: 'España',
        titleEn: 'Spain',
        phoneCode: '+34',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/es.svg',
    },
    {
        codeIso: 'LK',
        title: 'ශ්‍රී ලංකාව',
        titleEn: 'Sri Lanka',
        phoneCode: '+94',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/lk.svg',
    },
    {
        codeIso: 'SD',
        title: 'السودان',
        titleEn: 'Sudan',
        phoneCode: '+249',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/sd.svg',
    },
    {
        codeIso: 'SR',
        title: 'Suriname',
        titleEn: 'Suriname',
        phoneCode: '+597',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/sr.svg',
    },
    {
        codeIso: 'SJ',
        title: 'Svalbard og Jan Mayen',
        titleEn: 'Svalbard and Jan Mayen',
        phoneCode: '+47',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/sj.svg',
    },
    {
        codeIso: 'SZ',
        title: 'eSwatini',
        titleEn: 'Swaziland',
        phoneCode: '+268',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/sz.svg',
    },
    {
        codeIso: 'SE',
        title: 'Sverige',
        titleEn: 'Sweden',
        phoneCode: '+46',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/se.svg',
    },
    {
        codeIso: 'CH',
        title: 'Schweiz/Suisse/Svizzera',
        titleEn: 'Switzerland',
        phoneCode: '+41',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ch.svg',
    },
    {
        codeIso: 'SY',
        title: 'سوريا',
        titleEn: 'Syrian Arab Republic',
        phoneCode: '+963',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/sy.svg',
    },
    {
        codeIso: 'TW',
        title: '臺灣',
        titleEn: 'Taiwan',
        phoneCode: '+886',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/tw.svg',
    },
    {
        codeIso: 'TJ',
        title: 'Тоҷикистон',
        titleEn: 'Tajikistan',
        phoneCode: '+992',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/tj.svg',
    },
    {
        codeIso: 'TZ',
        title: 'Tanzania',
        titleEn: 'Tanzania, United Republic of Tanzania',
        phoneCode: '+255',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/tz.svg',
    },
    {
        codeIso: 'TH',
        title: 'ประเทศไทย',
        titleEn: 'Thailand',
        phoneCode: '+66',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/th.svg',
    },
    {
        codeIso: 'TL',
        title: 'Timór-Leste',
        titleEn: 'Timor-Leste',
        phoneCode: '+670',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/tl.svg',
    },
    {
        codeIso: 'TG',
        title: 'Togo',
        titleEn: 'Togo',
        phoneCode: '+228',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/tg.svg',
    },
    {
        codeIso: 'TK',
        title: 'Tokelau',
        titleEn: 'Tokelau',
        phoneCode: '+690',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/tk.svg',
    },
    {
        codeIso: 'TO',
        title: 'Tonga',
        titleEn: 'Tonga',
        phoneCode: '+676',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/to.svg',
    },
    {
        codeIso: 'TT',
        title: 'Trinidad and Tobago',
        titleEn: 'Trinidad and Tobago',
        phoneCode: '+1 868',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/tt.svg',
    },
    {
        codeIso: 'TN',
        title: 'تونس',
        titleEn: 'Tunisia',
        phoneCode: '+216',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/tn.svg',
    },
    {
        codeIso: 'TR',
        title: 'Türkiye',
        titleEn: 'Turkey',
        phoneCode: '+90',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/tr.svg',
    },
    {
        codeIso: 'TM',
        title: 'Türkmenistan',
        titleEn: 'Turkmenistan',
        phoneCode: '+993',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/tm.svg',
    },
    {
        codeIso: 'TC',
        title: 'Turks and Caicos Islands',
        titleEn: 'Turks and Caicos Islands',
        phoneCode: '+1 649',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/tc.svg',
    },
    {
        codeIso: 'TV',
        title: 'Tuvalu',
        titleEn: 'Tuvalu',
        phoneCode: '+688',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/tv.svg',
    },
    {
        codeIso: 'UG',
        title: 'Uganda',
        titleEn: 'Uganda',
        phoneCode: '+256',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ug.svg',
    },
    {
        codeIso: 'UA',
        title: 'Україна',
        titleEn: 'Ukraine',
        phoneCode: '+380',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ua.svg',
    },
    {
        codeIso: 'AE',
        title: 'الإمارات العربية المتحدة',
        titleEn: 'United Arab Emirates',
        phoneCode: '+971',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ae.svg',
    },
    {
        codeIso: 'GB',
        title: 'United Kingdom',
        titleEn: 'United Kingdom',
        phoneCode: '+44',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/gb.svg',
    },
    {
        codeIso: 'US',
        title: 'United States',
        titleEn: 'United States',
        phoneCode: '+1',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/us.svg',
    },
    {
        codeIso: 'UY',
        title: 'Uruguay',
        titleEn: 'Uruguay',
        phoneCode: '+598',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/uy.svg',
    },
    {
        codeIso: 'UZ',
        title: 'Oʻzbekiston',
        titleEn: 'Uzbekistan',
        phoneCode: '+998',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/uz.svg',
    },
    {
        codeIso: 'VU',
        title: 'Vanuatu',
        titleEn: 'Vanuatu',
        phoneCode: '+678',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/vu.svg',
    },
    {
        codeIso: 'VE',
        title: 'Venezuela',
        titleEn: 'Venezuela, Bolivarian Republic of Venezuela',
        phoneCode: '+58',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ve.svg',
    },
    {
        codeIso: 'VN',
        title: 'Việt Nam',
        titleEn: 'Vietnam',
        phoneCode: '+84',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/vn.svg',
    },
    {
        codeIso: 'VG',
        title: 'Virgin Islands, British',
        titleEn: 'Virgin Islands, British',
        phoneCode: '+1 284',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/vg.svg',
    },
    {
        codeIso: 'VI',
        title: 'Virgin Islands, U.S',
        titleEn: 'Virgin Islands, U.S.',
        phoneCode: '+1 340',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/vi.svg',
    },
    {
        codeIso: 'WF',
        title: 'Wallis and Futuna',
        titleEn: 'Wallis and Futuna',
        phoneCode: '+681',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/wf.svg',
    },
    {
        codeIso: 'YE',
        title: 'اليَمَن',
        titleEn: 'Yemen',
        phoneCode: '+967',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/ye.svg',
    },
    {
        codeIso: 'ZM',
        title: 'Zambia',
        titleEn: 'Zambia',
        phoneCode: '+260',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/zm.svg',
    },
    {
        codeIso: 'ZW',
        title: 'Zimbabwe',
        titleEn: 'Zimbabwe',
        phoneCode: '+263',
        imageUrl: 'https://api.jjo.finance/public/icons/countries-4x3/zw.svg',
    },
];
