name: Build Changed

on:
  push:
    branches:
      - 'release-*'
      - 'hotfix-*'
      - 'KOOP-*'
      - 'main'
env:
  SERVICE_NAME: coop-landing-v2
  ZENDESK_URL: https://jjoapp.zendesk.com/api/v2/help_center
  NEXT_PUBLIC_API_DOMAIN: https://api-dev.jjo.finance
  NEXT_SHARP_PATH: /tmp/node_modules/sharp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Build
      run: |
        docker build -t ghcr.io/jjoinvest/$SERVICE_NAME:${GITHUB_REF##*/} . --build-arg ZENDESK_URL=$ZENDESK_URL --build-arg ZENDESK_TOKEN=${{ secrets.ZENDESK_TOKEN }}
        docker push ghcr.io/jjoinvest/$SERVICE_NAME:${GITHUB_REF##*/}
        echo "Success build for ${SERVICE_NAME}:${GITHUB_REF##*/}"
        echo "SUCCESS_BUILD=1" >> $GITHUB_ENV
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_HTZ_DEV_CONFIG }}
    - name: Helm deploy
      run: |
        helm registry login ghcr.io/jjoinvest/jjo-helm-charts -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        helm fetch oci://ghcr.io/jjoinvest/jjo-helm-charts/jjo --version 1.0.0 --untar
        helm upgrade --install $SERVICE_NAME \
        -n default \
        --create-namespace \
        --set image.tag="${GITHUB_REF##*/}" \
        -f helm/values.yaml \
        jjo
